### ISSUE TITLE
Ability to Right-click > Copy Text.

### ISSUE THREAD

**Issue by no0nehere** [ravimohan1991/ChatDiamond#1]
and be able to paste it into other applications/discord.

**Comment by ravimohan1991** [comment]
Ok I have started working on the request 
(Clubbed along with url highlighter)

**Comment by no0nehere** [comment]
good luck!

**Comment by ravimohan1991** [comment]
Just posting that here. Hope our friend Que won't mind

![image](https://user-images.githubusercontent.com/2173654/208325965-87ae4bde-4a0f-4998-8375-080178627ea3.png)

Helps a ton with documentation in code.

**Comment by ravimohan1991** [comment]
So with port, game server ip information is loaded and without port webserver takes over!
![image](https://user-images.githubusercontent.com/2173654/208335114-c32b054b-5b10-4e4c-b2fa-8a4c3529a851.png)

**Comment by no0nehere** [comment]
great.

when i copy the server ip from the browser this is what i get;
45.61.53.244:6666
will that work as a server ip as it has a port also.

**Comment by ravimohan1991** [comment]
I think so! (if by server you mean game server)

If you refer to web server, then no, for now. Better standard needs to be suggested!!

The default game server port seems to be ```7777```. So players shall be forced to type complete port if they want to share clickable game server ip in the game.

**Comment by ravimohan1991** [comment]
![image](https://user-images.githubusercontent.com/2173654/208363776-69136f58-5ac7-4fa2-9e9d-248e84e5761d.png)

With the commit [```915d```](https://github.com/ravimohan1991/ChatDiamond/commit/915d76a52712da4fe1e8e49d47c795744364e28c), the feature has been successfully incorporated.
