### ISSUE TITLE
[469c] Eagle head icon sometimes leaks and appears in the game in random places

### ISSUE THREAD

**Issue by garry-ut99** [ravimohan1991/ChatDiamond#16]
I've found another issue: what are these animal faces that appear in the game in random places and why they appear unnecessarily? They appear not always, but sometimes, but often enought to be annoying, seem like some emojis leaking to game rendering?

![ss](https://github.com/ravimohan1991/ChatDiamond/assets/72945564/dbb12221-0450-4d5a-86b2-5022069fef29)

**Comment by ravimohan1991** [comment]
Thanks for notifying. Appearance of eagle head in mods, unexpectedly, is certainly not unheard of. Let me investigate by looking into the already known causes.
